export const SHOW_PETS = 'SHOW_PETS'
export const SHOW_PETS_MACHOS = 'SHOW_PETS_MACHOS'
export const SHOW_PETS_HEMBRAS = 'SHOW_PETS_HEMBRAS'
export const SHOW_PET = 'SHOW_PET'
export const ADD_PET = 'ADD_PET'
export const UPDATE_PET = 'UPDATE_PET'
export const DELETE_PET = 'DELETE_PET'